config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "products#index"
  resources :products
  # resources :checkout, only: [:create]
  post "checkout/create", to: "checkout#create"
  resources :webhooks, only: [:create]
  get "success", to: "checkout#success"
  get "cancel", to: "checkout#cancel"

  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product.rb
class Product < ApplicationRecord

    validates :name, :price, :price_cents, :currency, presence: true
    
    # to call just the product, without name
    def to_s
        name
    end

    monetize :price, as: :price_cents

    def to_builder
      Jbuilder.new do |product|        
        product.price stripe_price_id        
        product.quantity 1
      end
    end


    after_create do
        product = Stripe::Product.create(name: name)

        price = Stripe::Price.create({
            unit_amount: self.price,
            currency: self.currency,
            # recurring: {interval: 'month'},
            product: product.id,
          })
        
        update({stripe_product_id: product.id, stripe_price_id: price.id })
    end

    #after_update :create_and_assign_new_stripe_price, if: :saved_change_to_price?
    # after_update :create_and_assign_new_stripe_price, if: :saved_change_to_currency?
    #after_update :update_and_assign_new_name, if: :saved_change_to_name?
    # after_update :update_and_assign_new_name, if: :saved_changes.keys

    after_update :create_and_assign_new_stripe_price
    
    def create_and_assign_new_stripe_price

      stripe_old_price = Stripe::Price.retrieve(self.stripe_price_id)
      if stripe_old_price.unit_amount != self.price || stripe_old_price.currency != self.currency      
        price = Stripe::Price.create({ 
          unit_amount: self.price,  
          currency: self.currency,    
          product: self.stripe_product_id
        })
        update({ stripe_price_id: price.id})
      end

      stripe_old_product = Stripe::Product.retrieve(self.stripe_product_id)
      Stripe::Product.update( self.stripe_product_id, name: self.name) if stripe_old_product.name != self.name        
     
      #product = Stripe::Product.update( self.stripe_product_id , name: self.name)
            
    end

    # def update_and_assign_new_name
    #   product = Stripe::Product.update( self.stripe_product_id, name: self.name)  
    # end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # write to the session cart
  def add_to_cart
    cart = session[:cart]
    id = params[:id].to_i
    new_currency = params[:new_currency]    
    if cart.count == 0
      session[:cart] << id unless session[:cart].include?(id)
      redirect_to products_path
    elsif cart.count >= 1 && new_currency == Product.find(cart[cart.count-1]).currency
      session[:cart] << id unless session[:cart].include?(id)
      redirect_to products_path      
    else
      flash[:danger]="You cannot add the products with the different currencies!"
      redirect_to products_path
    end
  end

  # delete product id from the session
  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to products_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :price_cents, :currency)
    end
end

app/views/products/_form.html.erb
<%= form_with(model: product, class: "contents") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price_cents %>
    <%= form.text_field :price_cents, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :currency %>
    <%= form.text_field :currency, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="group relative">
  <div id="<%= dom_id product %>">
    <p class="my-5">
      <strong class="block font-medium mb-1">Name:</strong>
      <%= product %>
    </p>
    <p class="my-5">
      <strong class="block font-medium mb-1">Price:</strong>
      <%#= number_to_currency(product.price.to_f/100) %>
      <%= product.price_cents %>
    </p>
    <p class="my-5">
      <strong class="block font-medium mb-1">Currency:</strong>
      <%= product.currency %>
    </p>
    <% if product.stripe_product_id %>
      <p class="my-5">
        <strong class="block font-medium mb-1">Stripe product id:</strong>
        <%= product.stripe_product_id %>
      </p>
    <% end %>
    <% if product.stripe_price_id %>
      <p class="my-5">
        <strong class="block font-medium mb-1">Stripe price id:</strong>
        <%= product.stripe_price_id %>
      </p>
    <% end %>
      <p class="my-5">
      <strong class="block font-medium mb-1">Sales count:</strong>
      <%= product.sales_count %>
    </p>

      <% if action_name != "show" %>
        <%= link_to "Show this product", product, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        <%= link_to "Edit this product", edit_product_path(product), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
      <hr class="mt-6">

        <% if @cart.include?(product) %>

          <%= button_to "Remove from cart", remove_from_cart_path(product), method: :delete, data:{"turbo-method": :delete, turbo_confirm: "Are you sure?"} %>
        <% else %>
          <%= button_to "Add to cart", add_to_cart_path(product), params: {"id":product.id, "new_currency":product.currency} %>
        <% end%>

    <% end %>
  </div>
        <div class="group relative">
        <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
          <img src="https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg" alt="Front of men&#039;s Basic Tee in black." class="h-full w-full object-cover object-center lg:h-full lg:w-full">
        </div>
        <div class="mt-4 flex justify-between">
          <div>
            <h3 class="text-sm text-gray-700">
              <a href="#">
                <span aria-hidden="true" class="absolute inset-0"></span>
                Basic Tee
              </a>
            </h3>
            <p class="mt-1 text-sm text-gray-500">Black</p>
          </div>
          <p class="text-sm font-medium text-gray-900">$35</p>
        </div>
      </div>
</div>

app/views/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Show this product", @product, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Products</h1>
    <%= link_to "New product", new_product_path,
    class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <%# <div id="products" class="min-w-full">
    <%= render @products %>
  <%# </div> %>
  <%= @cart %><hr><hr>
      <% if @cart.present? %>

      <% if @cart.count > 1 && @cart[@cart.count-2].currency != @cart[@cart.count-1].currency %>
      <%=  @cart[@cart.count-1].currency %>
      <%= flash.now[:danger]= "You cannot add products with different currencies! "%>
      <%end%>

        <%= @cart.map { |item| item.to_builder.attributes! } %>
        <%= button_to "Payment", checkout_create_path, data: { disable_with: "validating .."}, data: { controller: "payment-button", action: "click->payment-button#handleClick"},
        class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
      <% end %>

  <div class="bg-white">
    <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
      <h2 class="text-2xl font-bold tracking-tight text-gray-900">Customers also purchased</h2>

      <div id="products" class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
        <%= render @products %>
      </div>

    </div>
</div>




</div>

app/views/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @product %>

    <%= link_to "Edit this product", edit_product_path(@product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this product", product_path(@product), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>