config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "products#index"
  resources :products
  # resources :checkout, only: [:create]
  post "checkout/create", to: "checkout#create"
  resources :webhooks, only: [:create]
  get "success", to: "checkout#success"
  get "cancel", to: "checkout#cancel"

  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_flash.html.erb
<% if flash.present? %>
    <div id="flash_message">
        <% flash.each do |type, msg| %>
            <div data-controller="alert" data-alert-target="hideable" class="alert-<%= type %> text-white px-4 py-3 rounded relative" role="alert">
                <div class="">
                    <strong class="font-bold text-white"><%= msg %></strong>
                    <div data-action="click->alert#hideMe">
                        <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                            <svg class="fill-current h-6 w-6 text-white" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
                        </span>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="fixed bottom-0 left-0 z-20 w-full p-4 bg-white border-t border-gray-200 shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800 dark:border-gray-600">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <%= link_to "DevEkma", "https://devekma.fun", target: :blank, class: "hover:underline" %>. All Rights Reserved.
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0">
        <li>
             <%= link_to "Privacy Policy", "https://devekma.fun/privacy-policy", target: :blank, class: "mr-4 hover:underline md:mr-6" %>
        </li>
        <li>
           <%= link_to "Contact", "mailto:support@devekma.fun", target: :blank, class: "mr-4 hover:underline md:mr-6" %>
        </li>
    </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900"><%= header %></h1>
    </div>
  </header>

app/views/layouts/_navbar.html.erb
 <%# <nav data-controller="menu-vertical" class="bg-gray-800"> %>
<%= content_tag(:nav, "", data: {controller: "menu-vertical"}, class:"bg-gray-800")  do %>
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <%= content_tag(:div, data: {action: "click->menu-vertical#dropdownHide"}, class:"absolute inset-y-0 left-0 flex items-center sm:hidden") do %>
      <%# <div data-action="click->menu-vertical#dropdownHide" class="absolute inset-y-0 left-0 flex items-center sm:hidden"> %>
        <!-- Mobile menu button-->
        <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!-- Icon when menu is closed. Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!-- Icon when menu is open. Menu open: "block", Menu closed: "hidden"-->
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      <% end %>
      <%# </div> %>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">        
          <%= link_to root_path, class: "btn btn-primary" do %>
            <i class="fa-solid fa-sd-card fa-xl" style="color: #62d092;"></i>            
          <% end %>
        </div>
        <%# if user_signed_in? %>
        <%= content_tag(:div, "", data: {controller: "menu"}, class:"hidden sm:ml-6 sm:block")  do %>
        <%# <div data-controller="menu" class="hidden sm:ml-6 sm:block"> %>
            <div class="flex space-x-4">
              <div class ="<%= 'rounded-md bg-gray-900' if request.path == "/" %>">
                <%= link_to 'Welcome', root_path, class: 'inline-flex w-full justify-center gap-x-1.5 rounded-md px-3 py-2 text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 text-sm font-medium' %>
              </div>
              <div class ="<%= 'rounded-md bg-gray-900' if request.path == "/products" %>">
                <%= link_to 'Products', products_path, class: 'inline-flex w-full justify-center gap-x-1.5 rounded-md px-3 py-2 text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 text-sm font-medium' %>
              </div>
              <%# Dropdown menu%>
              <div data-action="menu#toggle" class="relative inline-block text-left <%= 'rounded-md bg-gray-900' if request.path == edit_user_registration_path %>">
                  <%= content_tag(:button, data: {action: "click->menu#toggle"}, class: "inline-flex w-full justify-center gap-x-1.5 rounded-md px-3 py-2 text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 text-sm font-medium") do%>
                  <%# <button data-action="menu#toggle" type="button" class="inline-flex w-full justify-center gap-x-1.5 rounded-md px-3 py-2 text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 text-sm font-medium" id="menu-button" aria-expanded="true" aria-haspopup="true"> %>
                    Profile
                    <svg class="-mr-1 h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
                    </svg>
                  <% end %>
                  <%# </button> %>
                
                <div data-menu-target="toggleable" class="absolute right-0 z-10000 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none hidden" 
                role="menu" aria-orientation="vertical" aria-labelledby="menu-button" style="z-index: 90000;">
                  <div class="py-1" role="none">
                    <%= link_to edit_user_registration_path, class:"text-gray-700 block px-4 py-2 text-sm" do %>
                    <i class="fa-solid fa-pen-to-square" style="padding: 0 5px 0 5px"></i>Edit profile
                    <% end %>
                    <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Account settings</a>
                    <form method="POST" action="#" role="none">
                      <button type="submit" class="text-gray-700 block w-full px-4 py-2 text-left text-sm" role="menuitem" tabindex="-1" id="menu-item-4">Sign out</button>
                    </form>
                  </div>
                </div>
              </div>
              <%# Dropdown menu end%>            
                <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Team</a>
            </div>
        <% end %>
        <%# </div> %>
        <%# end %>
      </div>

      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <%# <%= current_user.id %>
        <% if user_signed_in? %>

        <ul class="space-y-4 text-left text-gray-300 dark:text-gray-400 hidden md:block" style="color: #a66cfe">
          <li class="flex items-center space-x-3 text-sm font-medium">
            <i class="fa-regular fa-solid fa-circle-user" style="color: #a66cfe; padding:0 5px 0 5px"></i><%= current_user.email %>
          </li>
        </ul>

        <% if current_user.stripe_customer_id.present? %>
            <div class="flex flex-shrink-0 items-center px-3 py-2">
              <ul class="space-y-4 text-left text-gray-300 dark:text-gray-400 hidden md:block" style="color: #a66cfe">
                <li class="flex items-center space-x-3 text-sm font-medium">
                  <%= current_user.stripe_customer_id %>
                </li>
              </ul>              
            </div>
          <% end %>
          <div class="flex flex-shrink-0 items-center px-3 py-2">
            <%= link_to destroy_user_session_path, data:{turbo_method: :delete}, class: "inline-flex w-full justify-center gap-x-1.5 rounded-md px-3 py-2 text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 text-sm font-medium" do %>
              Logout           
            <% end %>
          </div>
        <% else %>
              <%= link_to "Login", new_user_session_path, class: "inline-flex w-full justify-center gap-x-1.5 rounded-md px-3 py-2 text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 text-sm font-medium" %>
        <% end %>
      </div>
    </div> 
  </div>
  
  <!-- Mobile menu, show/hide based on menu state. -->
  <div data-menu-vertical-target="dropdownable" class="sm:hidden relative hidden" id="mobile-menu">
    <div class="mt-4 bg-white shadow-lg origin-top-right rounded-md ring-1 ring-black ring-opacity-5 fixed top-10 left-0 right-0" style="z-index: 90000;">
      <a href="#" class="bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium text-gray-700" aria-current="page">Welcome</a>
      <a href="#" class="text-gray-700 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium ">My Friends</a>
      <%# Dropdown menu%>
      <div data-controller="menu" class="static text-left mx-auto">
        <div>
          <button data-action="menu#toggle" type="button" class="inline-flex w-full justify-left gap-x-1.5 rounded-md px-3 py-2 text-gray-700 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" id="menu-button" aria-expanded="true" aria-haspopup="true">
            Profile
            <svg class="-mr-1 h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
            </svg>
          </button>
        </div>
        <div data-menu-target="toggleable" class="relative rounded-md bg-white ring-1 ring-black ring-opacity-5 focus:outline-none hidden" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
          <%= link_to edit_user_registration_path, class:"text-gray-700 block px-4 py-2 text-sm" do %>
              <i class="fa-solid fa-pen-to-square" style="padding: 0 5px 0 5px"></i>Edit profile
          <% end %>
          <div class="py-1" role="none">
            <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
            <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Account settings</a>
          </div>

        </div>
      </div>
      <%# Dropdown menu end%>   
      <a href="#" class="text-gray-700 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Projects</a>
      <a href="#" class="text-gray-700 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Calendar</a>      
    </div>
  </div>
<% end %>
<%# </nav> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoplify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <!-- <body>
    <%= link_to 'Products', products_path %>
    <hr/>
    <main class="container mx-auto mt-28 px-5 flex">
        <p class="notice"><%= notice %></p> 
       <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body> -->

  <body>
  <div id="reload"></div>
    <div class="min-h-full">
      <%= render 'layouts/navbar' %>
      <%#= render 'layouts/header', header: request.path == '/users/edit' ? 'Profile' : "Dashboard"  %>
      <main class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
      <%= render "layouts/flash"%>      
        <%= yield %>
      </main>
      <%= render partial: "layouts/footer" %>
    </div>
  </body>

</html>